"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import BillingCards from "./BillingCards";

type Project={id:string;name:string;updatedAt:string}; type Me={user:{name:string|null;email:string};subscription:{plan:string;status:string;downloadsUsed:number;downloadLimit:number|null;renewsAt:string|null}|null};
export default function DashboardClient(){const [me,setMe]=useState<Me|null>(null);const [projects,setProjects]=useState<Project[]>([]);const [showBilling,setShowBilling]=useState(false);const [loading,setLoading]=useState(true);
useEffect(()=>{Promise.all([fetch("/api/me").then(r=>r.json()),fetch("/api/projects").then(r=>r.json())]).then(([m,p])=>{setMe(m);setProjects(p.projects||[])}).finally(()=>setLoading(false))},[]);
async function signout(){await fetch("/api/auth/signout",{method:"POST"});window.location.href="/"}
if(loading)return <div className="p-10">Loading…</div>;
const s=me?.subscription; const quota=s?.downloadLimit===null?"Unlimited":`${s?.downloadsUsed ?? 0} / ${s?.downloadLimit ?? 0}`;
return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="font-black">BoxShot<span className="text-indigo-500">.</span></Link><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-500 sm:block">{me?.user.email}</span><button onClick={signout} className="rounded-lg px-3 py-2 text-sm hover:bg-slate-100">Sign out</button></div></div></header><div className="mx-auto max-w-6xl px-6 py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-black">Your projects</h1><p className="mt-1 text-slate-500">Create, save and download your box shots.</p></div><Link href="/editor" className="rounded-xl bg-slate-950 px-5 py-3 text-center font-semibold text-white">+ New project</Link></div><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_330px]"><section><div className="grid gap-4 sm:grid-cols-2">{projects.map(p=><Link key={p.id} href={`/editor?id=${p.id}`} className="rounded-2xl border bg-white p-5 hover:border-indigo-300"><div className="aspect-video rounded-xl bg-slate-100"/><h3 className="mt-4 font-bold">{p.name}</h3><p className="mt-1 text-xs text-slate-400">Updated {new Date(p.updatedAt).toLocaleDateString()}</p></Link>)}{projects.length===0&&<div className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500 sm:col-span-2">No projects yet. Create your first box shot.</div>}</div></section><aside className="rounded-2xl border bg-white p-6 h-fit"><p className="text-sm text-slate-500">Current plan</p><h2 className="mt-1 text-2xl font-black">{s?.plan ? s.plan.toUpperCase() : "FREE"}</h2><p className="mt-2 text-sm">Downloads: <b>{quota}</b></p><button onClick={()=>setShowBilling(v=>!v)} className="mt-5 w-full rounded-xl border px-4 py-3 text-sm font-semibold">{s?"Change plan":"Choose a plan"}</button></aside></div>{showBilling&&<div className="mt-8"><BillingCards/></div>}</div></main>}
